// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGeVjIxOpvgXZpjmBN5vdVW9p1Ig_wDE0',
    appId: '1:172224870478:web:628ac715cff32179826b1f',
    messagingSenderId: '172224870478',
    projectId: 'apps-efbb3',
    authDomain: 'apps-efbb3.firebaseapp.com',
    storageBucket: 'apps-efbb3.appspot.com',
    measurementId: 'G-YGLB8B6GX4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo-o75ZNB256ijBtLFIQGmiXoBSqf8o2Y',
    appId: '1:172224870478:android:88a2b1186ce674f5826b1f',
    messagingSenderId: '172224870478',
    projectId: 'apps-efbb3',
    storageBucket: 'apps-efbb3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfAGoDjum_MD7S2A2ew9E7vVd8em7J8B8',
    appId: '1:172224870478:ios:2b257232f0335a09826b1f',
    messagingSenderId: '172224870478',
    projectId: 'apps-efbb3',
    storageBucket: 'apps-efbb3.appspot.com',
    iosClientId: '172224870478-e44thguimr9ftp4rpcaglamskmag40ov.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicatioaserwerwr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfAGoDjum_MD7S2A2ew9E7vVd8em7J8B8',
    appId: '1:172224870478:ios:83fe72a9979fbb7d826b1f',
    messagingSenderId: '172224870478',
    projectId: 'apps-efbb3',
    storageBucket: 'apps-efbb3.appspot.com',
    iosClientId: '172224870478-8sp4522cpjrqh2ho6492heckbal345a8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicatioaserwerwr.RunnerTests',
  );
}
